// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: binlog.proto

package protocol;

public final class BinlogProto {
  private BinlogProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protocol.BinlogType}
   */
  public enum BinlogType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>INSERT = 0;</code>
     */
    INSERT(0),
    /**
     * <code>UPDATE = 1;</code>
     */
    UPDATE(1),
    /**
     * <code>DELETE = 2;</code>
     */
    DELETE(2),
    /**
     * <code>DDL = 3;</code>
     */
    DDL(3),
    ;

    /**
     * <code>INSERT = 0;</code>
     */
    public static final int INSERT_VALUE = 0;
    /**
     * <code>UPDATE = 1;</code>
     */
    public static final int UPDATE_VALUE = 1;
    /**
     * <code>DELETE = 2;</code>
     */
    public static final int DELETE_VALUE = 2;
    /**
     * <code>DDL = 3;</code>
     */
    public static final int DDL_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BinlogType valueOf(int value) {
      return forNumber(value);
    }

    public static BinlogType forNumber(int value) {
      switch (value) {
        case 0: return INSERT;
        case 1: return UPDATE;
        case 2: return DELETE;
        case 3: return DDL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BinlogType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BinlogType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BinlogType>() {
            public BinlogType findValueByNumber(int number) {
              return BinlogType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocol.BinlogProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final BinlogType[] VALUES = values();

    public static BinlogType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BinlogType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protocol.BinlogType)
  }

  public interface BinlogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.Binlog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string postion = 1;</code>
     */
    boolean hasPostion();
    /**
     * <code>optional string postion = 1;</code>
     */
    java.lang.String getPostion();
    /**
     * <code>optional string postion = 1;</code>
     */
    com.google.protobuf.ByteString
        getPostionBytes();

    /**
     * <code>optional string dbName = 2;</code>
     */
    boolean hasDbName();
    /**
     * <code>optional string dbName = 2;</code>
     */
    java.lang.String getDbName();
    /**
     * <code>optional string dbName = 2;</code>
     */
    com.google.protobuf.ByteString
        getDbNameBytes();

    /**
     * <code>optional .protocol.BinlogType type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>optional .protocol.BinlogType type = 3;</code>
     */
    protocol.BinlogProto.BinlogType getType();

    /**
     * <code>optional int32 columnCount = 4 [default = 0];</code>
     */
    boolean hasColumnCount();
    /**
     * <code>optional int32 columnCount = 4 [default = 0];</code>
     */
    int getColumnCount();

    /**
     * <code>optional string primaryKey = 5;</code>
     */
    boolean hasPrimaryKey();
    /**
     * <code>optional string primaryKey = 5;</code>
     */
    java.lang.String getPrimaryKey();
    /**
     * <code>optional string primaryKey = 5;</code>
     */
    com.google.protobuf.ByteString
        getPrimaryKeyBytes();

    /**
     * <code>optional string primaryValue = 6;</code>
     */
    boolean hasPrimaryValue();
    /**
     * <code>optional string primaryValue = 6;</code>
     */
    java.lang.String getPrimaryValue();
    /**
     * <code>optional string primaryValue = 6;</code>
     */
    com.google.protobuf.ByteString
        getPrimaryValueBytes();

    /**
     * <code>repeated .protocol.Row rows = 7;</code>
     */
    java.util.List<protocol.BinlogProto.Row> 
        getRowsList();
    /**
     * <code>repeated .protocol.Row rows = 7;</code>
     */
    protocol.BinlogProto.Row getRows(int index);
    /**
     * <code>repeated .protocol.Row rows = 7;</code>
     */
    int getRowsCount();
    /**
     * <code>repeated .protocol.Row rows = 7;</code>
     */
    java.util.List<? extends protocol.BinlogProto.RowOrBuilder> 
        getRowsOrBuilderList();
    /**
     * <code>repeated .protocol.Row rows = 7;</code>
     */
    protocol.BinlogProto.RowOrBuilder getRowsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protocol.Binlog}
   */
  public  static final class Binlog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.Binlog)
      BinlogOrBuilder {
    // Use Binlog.newBuilder() to construct.
    private Binlog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Binlog() {
      postion_ = "";
      dbName_ = "";
      type_ = 0;
      columnCount_ = 0;
      primaryKey_ = "";
      primaryValue_ = "";
      rows_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Binlog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              postion_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              dbName_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              protocol.BinlogProto.BinlogType value = protocol.BinlogProto.BinlogType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = rawValue;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              columnCount_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              primaryKey_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              primaryValue_ = bs;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                rows_ = new java.util.ArrayList<protocol.BinlogProto.Row>();
                mutable_bitField0_ |= 0x00000040;
              }
              rows_.add(
                  input.readMessage(protocol.BinlogProto.Row.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.BinlogProto.internal_static_protocol_Binlog_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.BinlogProto.internal_static_protocol_Binlog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.BinlogProto.Binlog.class, protocol.BinlogProto.Binlog.Builder.class);
    }

    private int bitField0_;
    public static final int POSTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object postion_;
    /**
     * <code>optional string postion = 1;</code>
     */
    public boolean hasPostion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string postion = 1;</code>
     */
    public java.lang.String getPostion() {
      java.lang.Object ref = postion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          postion_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string postion = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPostionBytes() {
      java.lang.Object ref = postion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        postion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DBNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object dbName_;
    /**
     * <code>optional string dbName = 2;</code>
     */
    public boolean hasDbName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string dbName = 2;</code>
     */
    public java.lang.String getDbName() {
      java.lang.Object ref = dbName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dbName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dbName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDbNameBytes() {
      java.lang.Object ref = dbName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>optional .protocol.BinlogType type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .protocol.BinlogType type = 3;</code>
     */
    public protocol.BinlogProto.BinlogType getType() {
      protocol.BinlogProto.BinlogType result = protocol.BinlogProto.BinlogType.valueOf(type_);
      return result == null ? protocol.BinlogProto.BinlogType.INSERT : result;
    }

    public static final int COLUMNCOUNT_FIELD_NUMBER = 4;
    private int columnCount_;
    /**
     * <code>optional int32 columnCount = 4 [default = 0];</code>
     */
    public boolean hasColumnCount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 columnCount = 4 [default = 0];</code>
     */
    public int getColumnCount() {
      return columnCount_;
    }

    public static final int PRIMARYKEY_FIELD_NUMBER = 5;
    private volatile java.lang.Object primaryKey_;
    /**
     * <code>optional string primaryKey = 5;</code>
     */
    public boolean hasPrimaryKey() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string primaryKey = 5;</code>
     */
    public java.lang.String getPrimaryKey() {
      java.lang.Object ref = primaryKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          primaryKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string primaryKey = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPrimaryKeyBytes() {
      java.lang.Object ref = primaryKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        primaryKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIMARYVALUE_FIELD_NUMBER = 6;
    private volatile java.lang.Object primaryValue_;
    /**
     * <code>optional string primaryValue = 6;</code>
     */
    public boolean hasPrimaryValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string primaryValue = 6;</code>
     */
    public java.lang.String getPrimaryValue() {
      java.lang.Object ref = primaryValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          primaryValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string primaryValue = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPrimaryValueBytes() {
      java.lang.Object ref = primaryValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        primaryValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROWS_FIELD_NUMBER = 7;
    private java.util.List<protocol.BinlogProto.Row> rows_;
    /**
     * <code>repeated .protocol.Row rows = 7;</code>
     */
    public java.util.List<protocol.BinlogProto.Row> getRowsList() {
      return rows_;
    }
    /**
     * <code>repeated .protocol.Row rows = 7;</code>
     */
    public java.util.List<? extends protocol.BinlogProto.RowOrBuilder> 
        getRowsOrBuilderList() {
      return rows_;
    }
    /**
     * <code>repeated .protocol.Row rows = 7;</code>
     */
    public int getRowsCount() {
      return rows_.size();
    }
    /**
     * <code>repeated .protocol.Row rows = 7;</code>
     */
    public protocol.BinlogProto.Row getRows(int index) {
      return rows_.get(index);
    }
    /**
     * <code>repeated .protocol.Row rows = 7;</code>
     */
    public protocol.BinlogProto.RowOrBuilder getRowsOrBuilder(
        int index) {
      return rows_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, postion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dbName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, columnCount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, primaryKey_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, primaryValue_);
      }
      for (int i = 0; i < rows_.size(); i++) {
        output.writeMessage(7, rows_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, postion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dbName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, columnCount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, primaryKey_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, primaryValue_);
      }
      for (int i = 0; i < rows_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, rows_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.BinlogProto.Binlog)) {
        return super.equals(obj);
      }
      protocol.BinlogProto.Binlog other = (protocol.BinlogProto.Binlog) obj;

      boolean result = true;
      result = result && (hasPostion() == other.hasPostion());
      if (hasPostion()) {
        result = result && getPostion()
            .equals(other.getPostion());
      }
      result = result && (hasDbName() == other.hasDbName());
      if (hasDbName()) {
        result = result && getDbName()
            .equals(other.getDbName());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasColumnCount() == other.hasColumnCount());
      if (hasColumnCount()) {
        result = result && (getColumnCount()
            == other.getColumnCount());
      }
      result = result && (hasPrimaryKey() == other.hasPrimaryKey());
      if (hasPrimaryKey()) {
        result = result && getPrimaryKey()
            .equals(other.getPrimaryKey());
      }
      result = result && (hasPrimaryValue() == other.hasPrimaryValue());
      if (hasPrimaryValue()) {
        result = result && getPrimaryValue()
            .equals(other.getPrimaryValue());
      }
      result = result && getRowsList()
          .equals(other.getRowsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPostion()) {
        hash = (37 * hash) + POSTION_FIELD_NUMBER;
        hash = (53 * hash) + getPostion().hashCode();
      }
      if (hasDbName()) {
        hash = (37 * hash) + DBNAME_FIELD_NUMBER;
        hash = (53 * hash) + getDbName().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasColumnCount()) {
        hash = (37 * hash) + COLUMNCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getColumnCount();
      }
      if (hasPrimaryKey()) {
        hash = (37 * hash) + PRIMARYKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPrimaryKey().hashCode();
      }
      if (hasPrimaryValue()) {
        hash = (37 * hash) + PRIMARYVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getPrimaryValue().hashCode();
      }
      if (getRowsCount() > 0) {
        hash = (37 * hash) + ROWS_FIELD_NUMBER;
        hash = (53 * hash) + getRowsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.BinlogProto.Binlog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.BinlogProto.Binlog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.BinlogProto.Binlog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.BinlogProto.Binlog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.BinlogProto.Binlog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.BinlogProto.Binlog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.BinlogProto.Binlog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.BinlogProto.Binlog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.BinlogProto.Binlog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.BinlogProto.Binlog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.BinlogProto.Binlog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.Binlog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.Binlog)
        protocol.BinlogProto.BinlogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.BinlogProto.internal_static_protocol_Binlog_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.BinlogProto.internal_static_protocol_Binlog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.BinlogProto.Binlog.class, protocol.BinlogProto.Binlog.Builder.class);
      }

      // Construct using protocol.BinlogProto.Binlog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRowsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        postion_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        dbName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        columnCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        primaryKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        primaryValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.BinlogProto.internal_static_protocol_Binlog_descriptor;
      }

      public protocol.BinlogProto.Binlog getDefaultInstanceForType() {
        return protocol.BinlogProto.Binlog.getDefaultInstance();
      }

      public protocol.BinlogProto.Binlog build() {
        protocol.BinlogProto.Binlog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.BinlogProto.Binlog buildPartial() {
        protocol.BinlogProto.Binlog result = new protocol.BinlogProto.Binlog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.postion_ = postion_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dbName_ = dbName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.columnCount_ = columnCount_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.primaryKey_ = primaryKey_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.primaryValue_ = primaryValue_;
        if (rowsBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            rows_ = java.util.Collections.unmodifiableList(rows_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.rows_ = rows_;
        } else {
          result.rows_ = rowsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.BinlogProto.Binlog) {
          return mergeFrom((protocol.BinlogProto.Binlog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.BinlogProto.Binlog other) {
        if (other == protocol.BinlogProto.Binlog.getDefaultInstance()) return this;
        if (other.hasPostion()) {
          bitField0_ |= 0x00000001;
          postion_ = other.postion_;
          onChanged();
        }
        if (other.hasDbName()) {
          bitField0_ |= 0x00000002;
          dbName_ = other.dbName_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasColumnCount()) {
          setColumnCount(other.getColumnCount());
        }
        if (other.hasPrimaryKey()) {
          bitField0_ |= 0x00000010;
          primaryKey_ = other.primaryKey_;
          onChanged();
        }
        if (other.hasPrimaryValue()) {
          bitField0_ |= 0x00000020;
          primaryValue_ = other.primaryValue_;
          onChanged();
        }
        if (rowsBuilder_ == null) {
          if (!other.rows_.isEmpty()) {
            if (rows_.isEmpty()) {
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureRowsIsMutable();
              rows_.addAll(other.rows_);
            }
            onChanged();
          }
        } else {
          if (!other.rows_.isEmpty()) {
            if (rowsBuilder_.isEmpty()) {
              rowsBuilder_.dispose();
              rowsBuilder_ = null;
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000040);
              rowsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRowsFieldBuilder() : null;
            } else {
              rowsBuilder_.addAllMessages(other.rows_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.BinlogProto.Binlog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.BinlogProto.Binlog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object postion_ = "";
      /**
       * <code>optional string postion = 1;</code>
       */
      public boolean hasPostion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string postion = 1;</code>
       */
      public java.lang.String getPostion() {
        java.lang.Object ref = postion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            postion_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string postion = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPostionBytes() {
        java.lang.Object ref = postion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          postion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string postion = 1;</code>
       */
      public Builder setPostion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        postion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string postion = 1;</code>
       */
      public Builder clearPostion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        postion_ = getDefaultInstance().getPostion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string postion = 1;</code>
       */
      public Builder setPostionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        postion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dbName_ = "";
      /**
       * <code>optional string dbName = 2;</code>
       */
      public boolean hasDbName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string dbName = 2;</code>
       */
      public java.lang.String getDbName() {
        java.lang.Object ref = dbName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dbName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dbName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDbNameBytes() {
        java.lang.Object ref = dbName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dbName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dbName = 2;</code>
       */
      public Builder setDbName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dbName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dbName = 2;</code>
       */
      public Builder clearDbName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dbName_ = getDefaultInstance().getDbName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dbName = 2;</code>
       */
      public Builder setDbNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dbName_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .protocol.BinlogType type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .protocol.BinlogType type = 3;</code>
       */
      public protocol.BinlogProto.BinlogType getType() {
        protocol.BinlogProto.BinlogType result = protocol.BinlogProto.BinlogType.valueOf(type_);
        return result == null ? protocol.BinlogProto.BinlogType.INSERT : result;
      }
      /**
       * <code>optional .protocol.BinlogType type = 3;</code>
       */
      public Builder setType(protocol.BinlogProto.BinlogType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .protocol.BinlogType type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      private int columnCount_ ;
      /**
       * <code>optional int32 columnCount = 4 [default = 0];</code>
       */
      public boolean hasColumnCount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 columnCount = 4 [default = 0];</code>
       */
      public int getColumnCount() {
        return columnCount_;
      }
      /**
       * <code>optional int32 columnCount = 4 [default = 0];</code>
       */
      public Builder setColumnCount(int value) {
        bitField0_ |= 0x00000008;
        columnCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 columnCount = 4 [default = 0];</code>
       */
      public Builder clearColumnCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        columnCount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object primaryKey_ = "";
      /**
       * <code>optional string primaryKey = 5;</code>
       */
      public boolean hasPrimaryKey() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string primaryKey = 5;</code>
       */
      public java.lang.String getPrimaryKey() {
        java.lang.Object ref = primaryKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            primaryKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string primaryKey = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPrimaryKeyBytes() {
        java.lang.Object ref = primaryKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          primaryKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string primaryKey = 5;</code>
       */
      public Builder setPrimaryKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        primaryKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string primaryKey = 5;</code>
       */
      public Builder clearPrimaryKey() {
        bitField0_ = (bitField0_ & ~0x00000010);
        primaryKey_ = getDefaultInstance().getPrimaryKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string primaryKey = 5;</code>
       */
      public Builder setPrimaryKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        primaryKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object primaryValue_ = "";
      /**
       * <code>optional string primaryValue = 6;</code>
       */
      public boolean hasPrimaryValue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string primaryValue = 6;</code>
       */
      public java.lang.String getPrimaryValue() {
        java.lang.Object ref = primaryValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            primaryValue_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string primaryValue = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPrimaryValueBytes() {
        java.lang.Object ref = primaryValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          primaryValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string primaryValue = 6;</code>
       */
      public Builder setPrimaryValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        primaryValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string primaryValue = 6;</code>
       */
      public Builder clearPrimaryValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        primaryValue_ = getDefaultInstance().getPrimaryValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string primaryValue = 6;</code>
       */
      public Builder setPrimaryValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        primaryValue_ = value;
        onChanged();
        return this;
      }

      private java.util.List<protocol.BinlogProto.Row> rows_ =
        java.util.Collections.emptyList();
      private void ensureRowsIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          rows_ = new java.util.ArrayList<protocol.BinlogProto.Row>(rows_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.BinlogProto.Row, protocol.BinlogProto.Row.Builder, protocol.BinlogProto.RowOrBuilder> rowsBuilder_;

      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public java.util.List<protocol.BinlogProto.Row> getRowsList() {
        if (rowsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rows_);
        } else {
          return rowsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public int getRowsCount() {
        if (rowsBuilder_ == null) {
          return rows_.size();
        } else {
          return rowsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public protocol.BinlogProto.Row getRows(int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);
        } else {
          return rowsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public Builder setRows(
          int index, protocol.BinlogProto.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.set(index, value);
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public Builder setRows(
          int index, protocol.BinlogProto.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.set(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public Builder addRows(protocol.BinlogProto.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public Builder addRows(
          int index, protocol.BinlogProto.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(index, value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public Builder addRows(
          protocol.BinlogProto.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public Builder addRows(
          int index, protocol.BinlogProto.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public Builder addAllRows(
          java.lang.Iterable<? extends protocol.BinlogProto.Row> values) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rows_);
          onChanged();
        } else {
          rowsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public Builder clearRows() {
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public Builder removeRows(int index) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.remove(index);
          onChanged();
        } else {
          rowsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public protocol.BinlogProto.Row.Builder getRowsBuilder(
          int index) {
        return getRowsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public protocol.BinlogProto.RowOrBuilder getRowsOrBuilder(
          int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);  } else {
          return rowsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public java.util.List<? extends protocol.BinlogProto.RowOrBuilder> 
           getRowsOrBuilderList() {
        if (rowsBuilder_ != null) {
          return rowsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rows_);
        }
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public protocol.BinlogProto.Row.Builder addRowsBuilder() {
        return getRowsFieldBuilder().addBuilder(
            protocol.BinlogProto.Row.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public protocol.BinlogProto.Row.Builder addRowsBuilder(
          int index) {
        return getRowsFieldBuilder().addBuilder(
            index, protocol.BinlogProto.Row.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.Row rows = 7;</code>
       */
      public java.util.List<protocol.BinlogProto.Row.Builder> 
           getRowsBuilderList() {
        return getRowsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.BinlogProto.Row, protocol.BinlogProto.Row.Builder, protocol.BinlogProto.RowOrBuilder> 
          getRowsFieldBuilder() {
        if (rowsBuilder_ == null) {
          rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocol.BinlogProto.Row, protocol.BinlogProto.Row.Builder, protocol.BinlogProto.RowOrBuilder>(
                  rows_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          rows_ = null;
        }
        return rowsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.Binlog)
    }

    // @@protoc_insertion_point(class_scope:protocol.Binlog)
    private static final protocol.BinlogProto.Binlog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.BinlogProto.Binlog();
    }

    public static protocol.BinlogProto.Binlog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Binlog>
        PARSER = new com.google.protobuf.AbstractParser<Binlog>() {
      public Binlog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Binlog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Binlog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Binlog> getParserForType() {
      return PARSER;
    }

    public protocol.BinlogProto.Binlog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RowOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.Row)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string column_name = 1;</code>
     */
    boolean hasColumnName();
    /**
     * <code>optional string column_name = 1;</code>
     */
    java.lang.String getColumnName();
    /**
     * <code>optional string column_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getColumnNameBytes();

    /**
     * <code>optional string column_type = 2;</code>
     */
    boolean hasColumnType();
    /**
     * <code>optional string column_type = 2;</code>
     */
    java.lang.String getColumnType();
    /**
     * <code>optional string column_type = 2;</code>
     */
    com.google.protobuf.ByteString
        getColumnTypeBytes();

    /**
     * <code>optional string column_value = 3;</code>
     */
    boolean hasColumnValue();
    /**
     * <code>optional string column_value = 3;</code>
     */
    java.lang.String getColumnValue();
    /**
     * <code>optional string column_value = 3;</code>
     */
    com.google.protobuf.ByteString
        getColumnValueBytes();

    /**
     * <code>optional string sql = 4;</code>
     */
    boolean hasSql();
    /**
     * <code>optional string sql = 4;</code>
     */
    java.lang.String getSql();
    /**
     * <code>optional string sql = 4;</code>
     */
    com.google.protobuf.ByteString
        getSqlBytes();
  }
  /**
   * Protobuf type {@code protocol.Row}
   */
  public  static final class Row extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.Row)
      RowOrBuilder {
    // Use Row.newBuilder() to construct.
    private Row(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Row() {
      columnName_ = "";
      columnType_ = "";
      columnValue_ = "";
      sql_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Row(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              columnName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              columnType_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              columnValue_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              sql_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.BinlogProto.internal_static_protocol_Row_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.BinlogProto.internal_static_protocol_Row_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.BinlogProto.Row.class, protocol.BinlogProto.Row.Builder.class);
    }

    private int bitField0_;
    public static final int COLUMN_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object columnName_;
    /**
     * <code>optional string column_name = 1;</code>
     */
    public boolean hasColumnName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string column_name = 1;</code>
     */
    public java.lang.String getColumnName() {
      java.lang.Object ref = columnName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          columnName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string column_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getColumnNameBytes() {
      java.lang.Object ref = columnName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        columnName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLUMN_TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object columnType_;
    /**
     * <code>optional string column_type = 2;</code>
     */
    public boolean hasColumnType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string column_type = 2;</code>
     */
    public java.lang.String getColumnType() {
      java.lang.Object ref = columnType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          columnType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string column_type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getColumnTypeBytes() {
      java.lang.Object ref = columnType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        columnType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLUMN_VALUE_FIELD_NUMBER = 3;
    private volatile java.lang.Object columnValue_;
    /**
     * <code>optional string column_value = 3;</code>
     */
    public boolean hasColumnValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string column_value = 3;</code>
     */
    public java.lang.String getColumnValue() {
      java.lang.Object ref = columnValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          columnValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string column_value = 3;</code>
     */
    public com.google.protobuf.ByteString
        getColumnValueBytes() {
      java.lang.Object ref = columnValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        columnValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SQL_FIELD_NUMBER = 4;
    private volatile java.lang.Object sql_;
    /**
     * <code>optional string sql = 4;</code>
     */
    public boolean hasSql() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string sql = 4;</code>
     */
    public java.lang.String getSql() {
      java.lang.Object ref = sql_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sql_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sql = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSqlBytes() {
      java.lang.Object ref = sql_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sql_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, columnName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, columnType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, columnValue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sql_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, columnName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, columnType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, columnValue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sql_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.BinlogProto.Row)) {
        return super.equals(obj);
      }
      protocol.BinlogProto.Row other = (protocol.BinlogProto.Row) obj;

      boolean result = true;
      result = result && (hasColumnName() == other.hasColumnName());
      if (hasColumnName()) {
        result = result && getColumnName()
            .equals(other.getColumnName());
      }
      result = result && (hasColumnType() == other.hasColumnType());
      if (hasColumnType()) {
        result = result && getColumnType()
            .equals(other.getColumnType());
      }
      result = result && (hasColumnValue() == other.hasColumnValue());
      if (hasColumnValue()) {
        result = result && getColumnValue()
            .equals(other.getColumnValue());
      }
      result = result && (hasSql() == other.hasSql());
      if (hasSql()) {
        result = result && getSql()
            .equals(other.getSql());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasColumnName()) {
        hash = (37 * hash) + COLUMN_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getColumnName().hashCode();
      }
      if (hasColumnType()) {
        hash = (37 * hash) + COLUMN_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getColumnType().hashCode();
      }
      if (hasColumnValue()) {
        hash = (37 * hash) + COLUMN_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getColumnValue().hashCode();
      }
      if (hasSql()) {
        hash = (37 * hash) + SQL_FIELD_NUMBER;
        hash = (53 * hash) + getSql().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.BinlogProto.Row parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.BinlogProto.Row parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.BinlogProto.Row parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.BinlogProto.Row parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.BinlogProto.Row parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.BinlogProto.Row parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.BinlogProto.Row parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.BinlogProto.Row parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.BinlogProto.Row parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.BinlogProto.Row parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.BinlogProto.Row prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.Row}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.Row)
        protocol.BinlogProto.RowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.BinlogProto.internal_static_protocol_Row_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.BinlogProto.internal_static_protocol_Row_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.BinlogProto.Row.class, protocol.BinlogProto.Row.Builder.class);
      }

      // Construct using protocol.BinlogProto.Row.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        columnName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        columnType_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        columnValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        sql_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.BinlogProto.internal_static_protocol_Row_descriptor;
      }

      public protocol.BinlogProto.Row getDefaultInstanceForType() {
        return protocol.BinlogProto.Row.getDefaultInstance();
      }

      public protocol.BinlogProto.Row build() {
        protocol.BinlogProto.Row result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.BinlogProto.Row buildPartial() {
        protocol.BinlogProto.Row result = new protocol.BinlogProto.Row(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.columnName_ = columnName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.columnType_ = columnType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.columnValue_ = columnValue_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sql_ = sql_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.BinlogProto.Row) {
          return mergeFrom((protocol.BinlogProto.Row)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.BinlogProto.Row other) {
        if (other == protocol.BinlogProto.Row.getDefaultInstance()) return this;
        if (other.hasColumnName()) {
          bitField0_ |= 0x00000001;
          columnName_ = other.columnName_;
          onChanged();
        }
        if (other.hasColumnType()) {
          bitField0_ |= 0x00000002;
          columnType_ = other.columnType_;
          onChanged();
        }
        if (other.hasColumnValue()) {
          bitField0_ |= 0x00000004;
          columnValue_ = other.columnValue_;
          onChanged();
        }
        if (other.hasSql()) {
          bitField0_ |= 0x00000008;
          sql_ = other.sql_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.BinlogProto.Row parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.BinlogProto.Row) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object columnName_ = "";
      /**
       * <code>optional string column_name = 1;</code>
       */
      public boolean hasColumnName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string column_name = 1;</code>
       */
      public java.lang.String getColumnName() {
        java.lang.Object ref = columnName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            columnName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string column_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getColumnNameBytes() {
        java.lang.Object ref = columnName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          columnName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string column_name = 1;</code>
       */
      public Builder setColumnName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        columnName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string column_name = 1;</code>
       */
      public Builder clearColumnName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        columnName_ = getDefaultInstance().getColumnName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string column_name = 1;</code>
       */
      public Builder setColumnNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        columnName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object columnType_ = "";
      /**
       * <code>optional string column_type = 2;</code>
       */
      public boolean hasColumnType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string column_type = 2;</code>
       */
      public java.lang.String getColumnType() {
        java.lang.Object ref = columnType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            columnType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string column_type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getColumnTypeBytes() {
        java.lang.Object ref = columnType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          columnType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string column_type = 2;</code>
       */
      public Builder setColumnType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        columnType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string column_type = 2;</code>
       */
      public Builder clearColumnType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        columnType_ = getDefaultInstance().getColumnType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string column_type = 2;</code>
       */
      public Builder setColumnTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        columnType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object columnValue_ = "";
      /**
       * <code>optional string column_value = 3;</code>
       */
      public boolean hasColumnValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string column_value = 3;</code>
       */
      public java.lang.String getColumnValue() {
        java.lang.Object ref = columnValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            columnValue_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string column_value = 3;</code>
       */
      public com.google.protobuf.ByteString
          getColumnValueBytes() {
        java.lang.Object ref = columnValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          columnValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string column_value = 3;</code>
       */
      public Builder setColumnValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        columnValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string column_value = 3;</code>
       */
      public Builder clearColumnValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        columnValue_ = getDefaultInstance().getColumnValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string column_value = 3;</code>
       */
      public Builder setColumnValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        columnValue_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sql_ = "";
      /**
       * <code>optional string sql = 4;</code>
       */
      public boolean hasSql() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string sql = 4;</code>
       */
      public java.lang.String getSql() {
        java.lang.Object ref = sql_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sql_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sql = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSqlBytes() {
        java.lang.Object ref = sql_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sql_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sql = 4;</code>
       */
      public Builder setSql(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sql_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sql = 4;</code>
       */
      public Builder clearSql() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sql_ = getDefaultInstance().getSql();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sql = 4;</code>
       */
      public Builder setSqlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sql_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.Row)
    }

    // @@protoc_insertion_point(class_scope:protocol.Row)
    private static final protocol.BinlogProto.Row DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.BinlogProto.Row();
    }

    public static protocol.BinlogProto.Row getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Row>
        PARSER = new com.google.protobuf.AbstractParser<Row>() {
      public Row parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Row(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Row> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Row> getParserForType() {
      return PARSER;
    }

    public protocol.BinlogProto.Row getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Binlog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Binlog_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Row_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Row_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014binlog.proto\022\010protocol\"\254\001\n\006Binlog\022\017\n\007p" +
      "ostion\030\001 \001(\t\022\016\n\006dbName\030\002 \001(\t\022\"\n\004type\030\003 \001" +
      "(\0162\024.protocol.BinlogType\022\026\n\013columnCount\030" +
      "\004 \001(\005:\0010\022\022\n\nprimaryKey\030\005 \001(\t\022\024\n\014primaryV" +
      "alue\030\006 \001(\t\022\033\n\004rows\030\007 \003(\0132\r.protocol.Row\"" +
      "R\n\003Row\022\023\n\013column_name\030\001 \001(\t\022\023\n\013column_ty" +
      "pe\030\002 \001(\t\022\024\n\014column_value\030\003 \001(\t\022\013\n\003sql\030\004 " +
      "\001(\t*9\n\nBinlogType\022\n\n\006INSERT\020\000\022\n\n\006UPDATE\020" +
      "\001\022\n\n\006DELETE\020\002\022\007\n\003DDL\020\003B\027\n\010protocolB\013Binl" +
      "ogProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_Binlog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Binlog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Binlog_descriptor,
        new java.lang.String[] { "Postion", "DbName", "Type", "ColumnCount", "PrimaryKey", "PrimaryValue", "Rows", });
    internal_static_protocol_Row_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_Row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Row_descriptor,
        new java.lang.String[] { "ColumnName", "ColumnType", "ColumnValue", "Sql", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
