// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: binlog.proto

package cdbBinlog.protocol;

public final class BinlogProto {
  private BinlogProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BinlogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.Binlog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 postion = 1;</code>
     */
    boolean hasPostion();
    /**
     * <code>optional uint64 postion = 1;</code>
     */
    long getPostion();

    /**
     * <code>optional string dbName = 2;</code>
     */
    boolean hasDbName();
    /**
     * <code>optional string dbName = 2;</code>
     */
    java.lang.String getDbName();
    /**
     * <code>optional string dbName = 2;</code>
     */
    com.google.protobuf.ByteString
        getDbNameBytes();

    /**
     * <code>optional string type = 3 [default = "UPDATE"];</code>
     */
    boolean hasType();
    /**
     * <code>optional string type = 3 [default = "UPDATE"];</code>
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 3 [default = "UPDATE"];</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional int32 columnCount = 4 [default = 0];</code>
     */
    boolean hasColumnCount();
    /**
     * <code>optional int32 columnCount = 4 [default = 0];</code>
     */
    int getColumnCount();

    /**
     * <code>optional string primaryKey = 5;</code>
     */
    boolean hasPrimaryKey();
    /**
     * <code>optional string primaryKey = 5;</code>
     */
    java.lang.String getPrimaryKey();
    /**
     * <code>optional string primaryKey = 5;</code>
     */
    com.google.protobuf.ByteString
        getPrimaryKeyBytes();

    /**
     * <code>optional string primaryValue = 6;</code>
     */
    boolean hasPrimaryValue();
    /**
     * <code>optional string primaryValue = 6;</code>
     */
    java.lang.String getPrimaryValue();
    /**
     * <code>optional string primaryValue = 6;</code>
     */
    com.google.protobuf.ByteString
        getPrimaryValueBytes();

    /**
     * <code>repeated bytes rows = 7;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getRowsList();
    /**
     * <code>repeated bytes rows = 7;</code>
     */
    int getRowsCount();
    /**
     * <code>repeated bytes rows = 7;</code>
     */
    com.google.protobuf.ByteString getRows(int index);
  }
  /**
   * Protobuf type {@code protocol.Binlog}
   */
  public  static final class Binlog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.Binlog)
      BinlogOrBuilder {
    // Use Binlog.newBuilder() to construct.
    private Binlog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Binlog() {
      postion_ = 0L;
      dbName_ = "";
      type_ = "UPDATE";
      columnCount_ = 0;
      primaryKey_ = "";
      primaryValue_ = "";
      rows_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Binlog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              postion_ = input.readUInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              dbName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              type_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              columnCount_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              primaryKey_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              primaryValue_ = bs;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                rows_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000040;
              }
              rows_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cdbBinlog.protocol.BinlogProto.internal_static_protocol_Binlog_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cdbBinlog.protocol.BinlogProto.internal_static_protocol_Binlog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cdbBinlog.protocol.BinlogProto.Binlog.class, cdbBinlog.protocol.BinlogProto.Binlog.Builder.class);
    }

    private int bitField0_;
    public static final int POSTION_FIELD_NUMBER = 1;
    private long postion_;
    /**
     * <code>optional uint64 postion = 1;</code>
     */
    public boolean hasPostion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 postion = 1;</code>
     */
    public long getPostion() {
      return postion_;
    }

    public static final int DBNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object dbName_;
    /**
     * <code>optional string dbName = 2;</code>
     */
    public boolean hasDbName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string dbName = 2;</code>
     */
    public java.lang.String getDbName() {
      java.lang.Object ref = dbName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dbName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dbName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDbNameBytes() {
      java.lang.Object ref = dbName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object type_;
    /**
     * <code>optional string type = 3 [default = "UPDATE"];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string type = 3 [default = "UPDATE"];</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string type = 3 [default = "UPDATE"];</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLUMNCOUNT_FIELD_NUMBER = 4;
    private int columnCount_;
    /**
     * <code>optional int32 columnCount = 4 [default = 0];</code>
     */
    public boolean hasColumnCount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 columnCount = 4 [default = 0];</code>
     */
    public int getColumnCount() {
      return columnCount_;
    }

    public static final int PRIMARYKEY_FIELD_NUMBER = 5;
    private volatile java.lang.Object primaryKey_;
    /**
     * <code>optional string primaryKey = 5;</code>
     */
    public boolean hasPrimaryKey() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string primaryKey = 5;</code>
     */
    public java.lang.String getPrimaryKey() {
      java.lang.Object ref = primaryKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          primaryKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string primaryKey = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPrimaryKeyBytes() {
      java.lang.Object ref = primaryKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        primaryKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIMARYVALUE_FIELD_NUMBER = 6;
    private volatile java.lang.Object primaryValue_;
    /**
     * <code>optional string primaryValue = 6;</code>
     */
    public boolean hasPrimaryValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string primaryValue = 6;</code>
     */
    public java.lang.String getPrimaryValue() {
      java.lang.Object ref = primaryValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          primaryValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string primaryValue = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPrimaryValueBytes() {
      java.lang.Object ref = primaryValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        primaryValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROWS_FIELD_NUMBER = 7;
    private java.util.List<com.google.protobuf.ByteString> rows_;
    /**
     * <code>repeated bytes rows = 7;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getRowsList() {
      return rows_;
    }
    /**
     * <code>repeated bytes rows = 7;</code>
     */
    public int getRowsCount() {
      return rows_.size();
    }
    /**
     * <code>repeated bytes rows = 7;</code>
     */
    public com.google.protobuf.ByteString getRows(int index) {
      return rows_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, postion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dbName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, columnCount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, primaryKey_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, primaryValue_);
      }
      for (int i = 0; i < rows_.size(); i++) {
        output.writeBytes(7, rows_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, postion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dbName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, columnCount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, primaryKey_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, primaryValue_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < rows_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(rows_.get(i));
        }
        size += dataSize;
        size += 1 * getRowsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cdbBinlog.protocol.BinlogProto.Binlog)) {
        return super.equals(obj);
      }
      cdbBinlog.protocol.BinlogProto.Binlog other = (cdbBinlog.protocol.BinlogProto.Binlog) obj;

      boolean result = true;
      result = result && (hasPostion() == other.hasPostion());
      if (hasPostion()) {
        result = result && (getPostion()
            == other.getPostion());
      }
      result = result && (hasDbName() == other.hasDbName());
      if (hasDbName()) {
        result = result && getDbName()
            .equals(other.getDbName());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && getType()
            .equals(other.getType());
      }
      result = result && (hasColumnCount() == other.hasColumnCount());
      if (hasColumnCount()) {
        result = result && (getColumnCount()
            == other.getColumnCount());
      }
      result = result && (hasPrimaryKey() == other.hasPrimaryKey());
      if (hasPrimaryKey()) {
        result = result && getPrimaryKey()
            .equals(other.getPrimaryKey());
      }
      result = result && (hasPrimaryValue() == other.hasPrimaryValue());
      if (hasPrimaryValue()) {
        result = result && getPrimaryValue()
            .equals(other.getPrimaryValue());
      }
      result = result && getRowsList()
          .equals(other.getRowsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPostion()) {
        hash = (37 * hash) + POSTION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPostion());
      }
      if (hasDbName()) {
        hash = (37 * hash) + DBNAME_FIELD_NUMBER;
        hash = (53 * hash) + getDbName().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasColumnCount()) {
        hash = (37 * hash) + COLUMNCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getColumnCount();
      }
      if (hasPrimaryKey()) {
        hash = (37 * hash) + PRIMARYKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPrimaryKey().hashCode();
      }
      if (hasPrimaryValue()) {
        hash = (37 * hash) + PRIMARYVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getPrimaryValue().hashCode();
      }
      if (getRowsCount() > 0) {
        hash = (37 * hash) + ROWS_FIELD_NUMBER;
        hash = (53 * hash) + getRowsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cdbBinlog.protocol.BinlogProto.Binlog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cdbBinlog.protocol.BinlogProto.Binlog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cdbBinlog.protocol.BinlogProto.Binlog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cdbBinlog.protocol.BinlogProto.Binlog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cdbBinlog.protocol.BinlogProto.Binlog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cdbBinlog.protocol.BinlogProto.Binlog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cdbBinlog.protocol.BinlogProto.Binlog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cdbBinlog.protocol.BinlogProto.Binlog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cdbBinlog.protocol.BinlogProto.Binlog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cdbBinlog.protocol.BinlogProto.Binlog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cdbBinlog.protocol.BinlogProto.Binlog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.Binlog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.Binlog)
        cdbBinlog.protocol.BinlogProto.BinlogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cdbBinlog.protocol.BinlogProto.internal_static_protocol_Binlog_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cdbBinlog.protocol.BinlogProto.internal_static_protocol_Binlog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cdbBinlog.protocol.BinlogProto.Binlog.class, cdbBinlog.protocol.BinlogProto.Binlog.Builder.class);
      }

      // Construct using cdbBinlog.protocol.BinlogProto.Binlog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        postion_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        dbName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = "UPDATE";
        bitField0_ = (bitField0_ & ~0x00000004);
        columnCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        primaryKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        primaryValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        rows_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cdbBinlog.protocol.BinlogProto.internal_static_protocol_Binlog_descriptor;
      }

      public cdbBinlog.protocol.BinlogProto.Binlog getDefaultInstanceForType() {
        return cdbBinlog.protocol.BinlogProto.Binlog.getDefaultInstance();
      }

      public cdbBinlog.protocol.BinlogProto.Binlog build() {
        cdbBinlog.protocol.BinlogProto.Binlog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cdbBinlog.protocol.BinlogProto.Binlog buildPartial() {
        cdbBinlog.protocol.BinlogProto.Binlog result = new cdbBinlog.protocol.BinlogProto.Binlog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.postion_ = postion_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dbName_ = dbName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.columnCount_ = columnCount_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.primaryKey_ = primaryKey_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.primaryValue_ = primaryValue_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.rows_ = rows_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cdbBinlog.protocol.BinlogProto.Binlog) {
          return mergeFrom((cdbBinlog.protocol.BinlogProto.Binlog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cdbBinlog.protocol.BinlogProto.Binlog other) {
        if (other == cdbBinlog.protocol.BinlogProto.Binlog.getDefaultInstance()) return this;
        if (other.hasPostion()) {
          setPostion(other.getPostion());
        }
        if (other.hasDbName()) {
          bitField0_ |= 0x00000002;
          dbName_ = other.dbName_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000004;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasColumnCount()) {
          setColumnCount(other.getColumnCount());
        }
        if (other.hasPrimaryKey()) {
          bitField0_ |= 0x00000010;
          primaryKey_ = other.primaryKey_;
          onChanged();
        }
        if (other.hasPrimaryValue()) {
          bitField0_ |= 0x00000020;
          primaryValue_ = other.primaryValue_;
          onChanged();
        }
        if (!other.rows_.isEmpty()) {
          if (rows_.isEmpty()) {
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureRowsIsMutable();
            rows_.addAll(other.rows_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cdbBinlog.protocol.BinlogProto.Binlog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cdbBinlog.protocol.BinlogProto.Binlog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long postion_ ;
      /**
       * <code>optional uint64 postion = 1;</code>
       */
      public boolean hasPostion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 postion = 1;</code>
       */
      public long getPostion() {
        return postion_;
      }
      /**
       * <code>optional uint64 postion = 1;</code>
       */
      public Builder setPostion(long value) {
        bitField0_ |= 0x00000001;
        postion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 postion = 1;</code>
       */
      public Builder clearPostion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        postion_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object dbName_ = "";
      /**
       * <code>optional string dbName = 2;</code>
       */
      public boolean hasDbName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string dbName = 2;</code>
       */
      public java.lang.String getDbName() {
        java.lang.Object ref = dbName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dbName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dbName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDbNameBytes() {
        java.lang.Object ref = dbName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dbName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dbName = 2;</code>
       */
      public Builder setDbName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dbName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dbName = 2;</code>
       */
      public Builder clearDbName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dbName_ = getDefaultInstance().getDbName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dbName = 2;</code>
       */
      public Builder setDbNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dbName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "UPDATE";
      /**
       * <code>optional string type = 3 [default = "UPDATE"];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string type = 3 [default = "UPDATE"];</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 3 [default = "UPDATE"];</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 3 [default = "UPDATE"];</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 3 [default = "UPDATE"];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 3 [default = "UPDATE"];</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }

      private int columnCount_ ;
      /**
       * <code>optional int32 columnCount = 4 [default = 0];</code>
       */
      public boolean hasColumnCount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 columnCount = 4 [default = 0];</code>
       */
      public int getColumnCount() {
        return columnCount_;
      }
      /**
       * <code>optional int32 columnCount = 4 [default = 0];</code>
       */
      public Builder setColumnCount(int value) {
        bitField0_ |= 0x00000008;
        columnCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 columnCount = 4 [default = 0];</code>
       */
      public Builder clearColumnCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        columnCount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object primaryKey_ = "";
      /**
       * <code>optional string primaryKey = 5;</code>
       */
      public boolean hasPrimaryKey() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string primaryKey = 5;</code>
       */
      public java.lang.String getPrimaryKey() {
        java.lang.Object ref = primaryKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            primaryKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string primaryKey = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPrimaryKeyBytes() {
        java.lang.Object ref = primaryKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          primaryKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string primaryKey = 5;</code>
       */
      public Builder setPrimaryKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        primaryKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string primaryKey = 5;</code>
       */
      public Builder clearPrimaryKey() {
        bitField0_ = (bitField0_ & ~0x00000010);
        primaryKey_ = getDefaultInstance().getPrimaryKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string primaryKey = 5;</code>
       */
      public Builder setPrimaryKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        primaryKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object primaryValue_ = "";
      /**
       * <code>optional string primaryValue = 6;</code>
       */
      public boolean hasPrimaryValue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string primaryValue = 6;</code>
       */
      public java.lang.String getPrimaryValue() {
        java.lang.Object ref = primaryValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            primaryValue_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string primaryValue = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPrimaryValueBytes() {
        java.lang.Object ref = primaryValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          primaryValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string primaryValue = 6;</code>
       */
      public Builder setPrimaryValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        primaryValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string primaryValue = 6;</code>
       */
      public Builder clearPrimaryValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        primaryValue_ = getDefaultInstance().getPrimaryValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string primaryValue = 6;</code>
       */
      public Builder setPrimaryValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        primaryValue_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> rows_ = java.util.Collections.emptyList();
      private void ensureRowsIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          rows_ = new java.util.ArrayList<com.google.protobuf.ByteString>(rows_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated bytes rows = 7;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getRowsList() {
        return java.util.Collections.unmodifiableList(rows_);
      }
      /**
       * <code>repeated bytes rows = 7;</code>
       */
      public int getRowsCount() {
        return rows_.size();
      }
      /**
       * <code>repeated bytes rows = 7;</code>
       */
      public com.google.protobuf.ByteString getRows(int index) {
        return rows_.get(index);
      }
      /**
       * <code>repeated bytes rows = 7;</code>
       */
      public Builder setRows(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRowsIsMutable();
        rows_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes rows = 7;</code>
       */
      public Builder addRows(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRowsIsMutable();
        rows_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes rows = 7;</code>
       */
      public Builder addAllRows(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureRowsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rows_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes rows = 7;</code>
       */
      public Builder clearRows() {
        rows_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.Binlog)
    }

    // @@protoc_insertion_point(class_scope:protocol.Binlog)
    private static final cdbBinlog.protocol.BinlogProto.Binlog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cdbBinlog.protocol.BinlogProto.Binlog();
    }

    public static cdbBinlog.protocol.BinlogProto.Binlog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Binlog>
        PARSER = new com.google.protobuf.AbstractParser<Binlog>() {
      public Binlog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Binlog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Binlog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Binlog> getParserForType() {
      return PARSER;
    }

    public cdbBinlog.protocol.BinlogProto.Binlog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Binlog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Binlog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014binlog.proto\022\010protocol\"\217\001\n\006Binlog\022\017\n\007p" +
      "ostion\030\001 \001(\004\022\016\n\006dbName\030\002 \001(\t\022\024\n\004type\030\003 \001" +
      "(\t:\006UPDATE\022\026\n\013columnCount\030\004 \001(\005:\0010\022\022\n\npr" +
      "imaryKey\030\005 \001(\t\022\024\n\014primaryValue\030\006 \001(\t\022\014\n\004" +
      "rows\030\007 \003(\014B!\n\022cdbBinlog.protocolB\013Binlog" +
      "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_Binlog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Binlog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Binlog_descriptor,
        new java.lang.String[] { "Postion", "DbName", "Type", "ColumnCount", "PrimaryKey", "PrimaryValue", "Rows", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
